### ISSUE TITLE
Must PV18 5248 PRO

### ISSUE THREAD

**Issue by AndriiBohak** [taHC81/MUST-ESPhome#6]
I have this devise, an try to connect but resieve wrong data, Is this integration compatible with this inverter?

![photo_5370887987430284901_y](https://github.com/user-attachments/assets/101c0172-738f-4dcd-9356-9b7975d86289)

**Comment by taHC81** [comment]
Hi, as you can see, probably not. Ask manufacturer or seller for the protocol (RS-485, modbus) and update YAML accordingly.

**Comment by taHC81** [comment]
Hi, as you can see, probably not. Ask manufacturer or seller for the protocol (RS-485, modbus) and update YAML accordingly.
